name: Run News Pipeline

on:
  schedule:
    # Runs every day at 7am, 1pm, 7pm IST (01:30, 07:30, 13:30 UTC)
    - cron: "30 1,7,13 * * *"
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        env:
          DB_URI: ${{ secrets.DB_URI }}
          NEWS_API: ${{ secrets.NEWS_API }}
        run: |
          python main.py
